/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

public class TriangleNumberCalculatorTest {

    TriangleNumberCalculator calculator = new TriangleNumberCalculator();

    @Test
    public void testValue() {
        assertEquals(0, calculator.value(0));
        assertEquals(21, calculator.value(6));
        assertEquals(36, calculator.value(8));
    }

    @Test
    public void testAdd() {
        assertEquals(70, calculator.add(10, 5));
        assertEquals(91, calculator.add(13, 0));
        assertEquals(66, calculator.add(6, 9));
    }

    @Test
    public void testSubtract() {
        assertEquals(5, calculator.subtract(5, 4));
        assertEquals(7, calculator.subtract(7, 6));
        assertEquals(6, calculator.subtract(6, 5));
    }
}